services:
  apiwpp:
    build: .
    container_name: apiwpp
    restart: always
    environment:
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    networks:
      - proxy

networks:
  proxy:
    external: true
